package scripts.CombatAIO.com.base.api.threading.types;

public enum ValueType {

	CURRENT_TARGET, MINIMUM_LOOT_VALUE, TOTAL_KILLS, TOTAL_LOOT_VALUE, ITEM_PRICE, LOOT_ITEM, AMOUNT_LOOTED_OF_ITEM, FOOD_NAME, MONSTER_NAMES, FIRST_MONSTER_NAME, HOME_TILE, IS_RANGING, RUN_TIME;

	ValueType() {
	}

}
