package scripts.CombatAIO.com.base.api.threading.types;

public enum ValueType {

	CURRENT_TARGET, MINIMUM_LOOT_VALUE, TOTAL_KILLS, TOTAL_LOOT_VALUE, ITEM_PRICE, LOOT_ITEM, AMOUNT_LOOTED_OF_ITEM, FOOD, MONSTER_NAMES, FIRST_MONSTER_NAME, HOME_TILE, IS_RANGING, RUN_TIME, FLICKER_PRAYER, EAT_FOR_SPACE, LOOT_ITEM_NAMES, IS_BONES_TO_PEACHES, WAIT_FOR_LOOT, LOOT_IN_COMBAT, SPECIAL_ATTACK_WEAPON, BANKER, POSSIBLE_MONSTERS, USE_GUTHANS, GUTHANS_IDS, ALL_LOOT_ITEMS;

	ValueType() {
	}
}
