package scripts.CombatAIO.com.base.api.tasks.types;

public enum ValueType {

	CURRENT_TARGET, MINIMUM_LOOT_VALUE, TOTAL_KILLS, TOTAL_LOOT_VALUE, ITEM_PRICE, LOOT_ITEM, AMOUNT_LOOTED_OF_ITEM, FOOD, HOME_TILE,

	IS_RANGING, RUN_TIME, PRAYER, EAT_FOR_SPACE, LOOT_ITEM_NAMES, IS_BONES_TO_PEACHES, WAIT_FOR_LOOT, LOOT_IN_COMBAT, SPECIAL_ATTACK_WEAPON,

	POSSIBLE_MONSTERS, USE_GUTHANS, GUTHANS_IDS, ALL_LOOT_ITEMS, FOOD_WITHDRAW_AMOUNT, FLICKER, MONSTER_IDS, COMBAT_RADIUS, WORLD_HOP_CONDITION, WORLD_HOP_VALUE,

	SAFE_SPOT_TILE, ARMOR_HOLDER_IDS, AMMO_ID, USE_TELEKINETIC_GRAB, USE_CANNON, CANNON_TILE, ATTACK_MONSTERS_IN_COMBAT, BURY_BONES, LOG_WHEN_OUT_OF_FOOD;

}
